import json

LANGUAGES = {
    "es": {
        "app_title": "PdfCopyCollector",
        "preferences": "Preferencias",
        "language": "Idioma",
        "theme_tooltip": "Cambiar tema",
        "settings": "Configuración",
        "files_section": "Archivos",
        "num_copies": "Número de Copias",
        "same_file_for_copies": "Usar mismo archivo para copias",
        "print_mode": "Modo de Impresión",
        "simplex": "Una cara",
        "duplex": "Doble cara",
        "insert_page": "Insertar página",
        "generate_fiery": "Generar archivo Fiery",
        "add_pdf": "Añadir PDF",
        "generate_pdf": "Ejecutar",
        "cancel": "Cancelar",
        "cancelling": "Cancelando...",
        "process_cancelled": "Proceso cancelado por el usuario.",
        "close_blocked_processing": "No se puede cerrar la app mientras se está creando el PDF.",
        "error": "Error",
        "warning": "Aviso",
        "same_file_requires_one": "Esta opción solo se puede activar cuando hay exactamente 1 archivo cargado.",
        "same_file_only_first": "Con esta opción activada, solo se usa el primer archivo seleccionado.",
        "success": "Éxito",
        "pdf_saved": "PDF generado correctamente.",
        "fiery_saved": "Archivo Fiery generado correctamente.",
        "invalid_copies": "El número de copias debe ser al menos 2.",
        "copies_less_than_loaded": "El número de copias no puede ser inferior a los archivos cargados ({0}).",
        "missing_files": "Faltan archivos. El número de archivos debe coincidir con el número de copias.",
        "different_pages": "Todos los archivos deben tener el mismo número de páginas que el archivo base ({0} páginas).",
        "duplex_odd_pages": "Para el modo a doble cara, el número de páginas del PDF debe ser par o se insertarán páginas en blanco.",
        "insert_source_one_page": "El PDF de página a insertar debe tener exactamente 1 página (actual: {0}).",
        "remove": "Eliminar",
        "pages": "páginas",
        "file_column": "Archivo",
        "page_short": "pág",
        "total_loaded": "Total cargado",
        "files_count": "Archivos",
        "progress_generating": "Generando páginas",
        "progress_flushing": "Guardando lote temporal",
        "progress_merging": "Uniendo lotes",
        "progress_saving": "Optimizando y guardando el PDF final, por favor espere...",
        "fiery_header": "Archivo Fiery - Xerox para Imposición - Generado el {0}",
        "fiery_mode": "Modo",
        "fiery_trays": "Cajones de papel",
        "fiery_apply_groups": "Aplicar cada grupo de copias a su papel correspondiente en su cajón.",
        "fiery_copy": "Copia",
        "fiery_mode_simplex": "UNA CARA",
        "fiery_mode_duplex": "DOBLE CARA",
        "info_version": "Juan Antonio Picornell Richarte\nVersion {0} - 2026",
        "invite_coffee": "Invítame a un café",
        "help_text_1": "Esta utilidad junta las páginas de varios archivos pdf en un nuevo archivo ordenando las páginas según sean a una cara o a doble cara y generando un archivo de configuración de cajones de papel para poder imprimir cada copia en un cajón diferente en máquinas digitales, en este caso para Fiery Command WorkStation.",
        "help_text_2": "Configure cuántas copias va a necesitar, configure si las copias son a una cara o a doble cara, cargue tantos archivos como copias en su orden, se generará un archivo que contiene todas las páginas de los archivos cargados y un archivo de configuración para Fiery Command WorkStation si ha marcado la casilla para su generación.",
        "help_text_insert": "Modo Insertar página: cargue primero el PDF maestro y después un PDF de 1 página. Esa misma página se insertará después de cada página del maestro.",
        "help_pdfcollector_title": "Modo PdfCollector",
        "help_pdfcollector_text": "PdfCollector une varios PDF en el orden cargado, sin reordenar páginas ni generar archivo Fiery. Puede cargar archivos con distinto número de páginas y obtener un único PDF final continuo.",
        "close": "Cerrar",
        "info": "Información",
        "pdf_optimization": "Optimización PDF",
        "opt_no_optimize": "PDF sin optimizar",
        "opt_standard": "PDF con fuentes optimizadas",
        "opt_no_duplicates": "PDF con fuentes e imágenes optimizadas",
        "help_opt_title": "Opciones de optimización PDF",
        "help_opt_no_optimize": "Más rápido, tamaño de archivo grande",
        "help_opt_standard": "Más lento, tamaño de archivo intermedio",
        "help_opt_no_duplicates": "Bastante lento, tamaño de archivo mínimo",
        "LICENSE_NOTICE": "Este programa es software libre: puedes redistribuirlo y/o modificarlo bajo los términos de la Licencia Pública General Affero de GNU (AGPL), versión 3. Se distribuye SIN NINGUNA GARANTÍA; consulta la licencia en gnu.org/licenses/agpl-3.0.html",
    },
    "en": {
        "app_title": "PdfCopyCollector",
        "preferences": "Preferences",
        "language": "Language",
        "theme_tooltip": "Change theme",
        "settings": "Settings",
        "files_section": "Files",
        "num_copies": "Number of Copies",
        "same_file_for_copies": "Use same file for copies",
        "print_mode": "Print Mode",
        "simplex": "Single-sided",
        "duplex": "Double-sided",
        "insert_page": "Insert page",
        "generate_fiery": "Generate Fiery file",
        "add_pdf": "Add PDF",
        "generate_pdf": "Run",
        "cancel": "Cancel",
        "cancelling": "Cancelling...",
        "process_cancelled": "Process cancelled by the user.",
        "close_blocked_processing": "The app cannot be closed while the PDF is being created.",
        "error": "Error",
        "warning": "Warning",
        "same_file_requires_one": "This option can only be enabled when exactly 1 file is loaded.",
        "same_file_only_first": "With this option enabled, only the first selected file will be used.",
        "success": "Success",
        "pdf_saved": "PDF generated successfully.",
        "fiery_saved": "Fiery file generated successfully.",
        "invalid_copies": "Number of copies must be at least 2.",
        "copies_less_than_loaded": "The number of copies cannot be less than the loaded files ({0}).",
        "missing_files": "Missing files. The number of files must match the number of copies.",
        "different_pages": "All files must have the same page count as the base file ({0} pages).",
        "duplex_odd_pages": "For double-sided mode, the PDF page count should be even or blank pages will be inserted.",
        "insert_source_one_page": "The insert-page PDF must contain exactly 1 page (current: {0}).",
        "remove": "Remove",
        "pages": "pages",
        "file_column": "File",
        "page_short": "pg",
        "total_loaded": "Total loaded",
        "files_count": "Files",
        "progress_generating": "Generating pages",
        "progress_flushing": "Saving temporary batch",
        "progress_merging": "Merging batches",
        "progress_saving": "Optimising and saving the final PDF, please wait...",
        "fiery_header": "Fiery File - Xerox for Imposition - Generated on {0}",
        "fiery_mode": "Mode",
        "fiery_trays": "Paper trays",
        "fiery_apply_groups": "Apply each group of copies to its corresponding paper in its tray.",
        "fiery_copy": "Copy",
        "fiery_mode_simplex": "SINGLE-SIDED",
        "fiery_mode_duplex": "DOUBLE-SIDED",
        "info_version": "Juan Antonio Picornell Richarte\nVersion {0} - 2026",
        "invite_coffee": "Buy me a coffee",
        "help_text_1": "This utility joins pages from several PDF files into a new file, ordering them based on single-sided or double-sided modes, and generating a paper tray configuration file to print each copy in a different tray on digital machines, specifically for Fiery Command WorkStation.",
        "help_text_2": "Set how many copies you will need, choose if they are single-sided or double-sided, load as many files as copies in their respective order. A new file containing all pages from the loaded files will be generated, along with a configuration file for Fiery Command WorkStation if the checkbox has been marked.",
        "help_text_insert": "Insert page mode: first load the master PDF, then load a 1-page PDF. That same page will be inserted after every page of the master.",
        "help_pdfcollector_title": "PdfCollector mode",
        "help_pdfcollector_text": "PdfCollector merges several PDFs in the loaded order, without reordering pages or generating a Fiery file. You can load files with different page counts and obtain one continuous final PDF.",
        "close": "Close",
        "info": "Information",
        "pdf_optimization": "PDF Optimization",
        "opt_no_optimize": "Unoptimized PDF",
        "opt_standard": "PDF with optimized fonts",
        "opt_no_duplicates": "PDF with optimized fonts and images",
        "help_opt_title": "PDF optimization options",
        "help_opt_no_optimize": "Faster, large file size",
        "help_opt_standard": "Slower, medium file size",
        "help_opt_no_duplicates": "Quite slow, minimum file size",
        "LICENSE_NOTICE": "This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License (AGPL), version 3. It is distributed WITHOUT ANY WARRANTY; see the license at gnu.org/licenses/agpl-3.0.html",
    },
    "cat": {
        "app_title": "PdfCopyCollector",
        "preferences": "Preferències",
        "language": "Llengua",
        "theme_tooltip": "Canviar tema",
        "settings": "Configuració",
        "files_section": "Fitxers",
        "num_copies": "Nombre de còpies",
        "same_file_for_copies": "Utilitzar el mateix fitxer per a les còpies",
        "print_mode": "Mode d'impressió",
        "simplex": "Una cara",
        "duplex": "Doble cara",
        "insert_page": "Inserir pàgina",
        "generate_fiery": "Generar fitxer Fiery",
        "add_pdf": "Afegir PDF",
        "generate_pdf": "Executar",
        "cancel": "Cancelar",
        "cancelling": "Cancel·lant...",
        "process_cancelled": "Procés cancel·lat per l'usuari.",
        "close_blocked_processing": "No es pot tancar l'app mentre s'està creant el PDF.",
        "error": "Error",
        "warning": "Avís",
        "same_file_requires_one": "Aquesta opció només es pot activar quan hi ha exactament 1 fitxer carregat.",
        "same_file_only_first": "Amb aquesta opció activada, només s'utilitzarà el primer fitxer seleccionat.",
        "success": "Èxit",
        "pdf_saved": "PDF generat correctament.",
        "fiery_saved": "Fitxer Fiery generat correctament.",
        "invalid_copies": "El nombre de còpies ha de ser com a mínim 2.",
        "copies_less_than_loaded": "El nombre de còpies no pot ser inferior als fitxers carregats ({0}).",
        "missing_files": "Falten fitxers. El nombre de fitxers ha de coincidir amb el nombre de còpies.",
        "different_pages": "Tots els fitxers han de tenir el mateix nombre de pàgines que el fitxer base ({0} pàgines).",
        "duplex_odd_pages": "Per al mode a doble cara, el nombre de pàgines del PDF ha de ser parell o s'inseriran pàgines en blanc.",
        "insert_source_one_page": "El PDF de pàgina a inserir ha de tenir exactament 1 pàgina (actual: {0}).",
        "remove": "Eliminar",
        "pages": "pàgines",
        "file_column": "Fitxer",
        "page_short": "pàg",
        "total_loaded": "Total carregat",
        "files_count": "Fitxers",
        "progress_generating": "Generant pàgines",
        "progress_flushing": "Desant lot temporal",
        "progress_merging": "Unint lots",
        "progress_saving": "Optimitzant i desant el PDF final, si us plau espereu...",
        "fiery_header": "Fitxer Fiery - Xerox per a imposició - Generat el {0}",
        "fiery_mode": "Mode",
        "fiery_trays": "Safates de paper",
        "fiery_apply_groups": "Aplica cada grup de còpies al paper corresponent de la seva safata.",
        "fiery_copy": "Còpia",
        "fiery_mode_simplex": "UNA CARA",
        "fiery_mode_duplex": "DOBLE CARA",
        "info_version": "Juan Antonio Picornell Richarte\nVersió {0} - 2026",
        "invite_coffee": "Convida'm a un cafè",
        "help_text_1": "Aquesta utilitat ajunta les pàgines de diversos fitxers PDF en un de nou ordenant les pàgines segons siguin a una cara o a doble cara i generant un fitxer de configuració de safates de paper per poder imprimir cada còpia en una safata diferent en màquines digitals, en aquest cas per a Fiery Command WorkStation.",
        "help_text_2": "Configureu quantes còpies necessitareu, si seran a una cara o a doble cara, i carregueu tants fitxers com còpies en el seu ordre. Es generarà un fitxer que contindrà totes les pàgines dels fitxers carregats i un fitxer de configuració per a Fiery Command WorkStation si heu marcat la casella per generar-lo.",
        "help_text_insert": "Mode Inserir pàgina: primer carregueu el PDF mestre i després un PDF d'1 pàgina. Aquesta mateixa pàgina s'inserirà després de cada pàgina del mestre.",
        "help_pdfcollector_title": "Mode PdfCollector",
        "help_pdfcollector_text": "PdfCollector uneix diversos PDF en l'ordre carregat, sense reordenar pàgines ni generar fitxer Fiery. Podeu carregar fitxers amb diferent nombre de pàgines i obtenir un únic PDF final continu.",
        "close": "Tancar",
        "info": "Informació",
        "pdf_optimization": "Optimització PDF",
        "opt_no_optimize": "PDF sense optimitzar",
        "opt_standard": "PDF amb fonts optimitzades",
        "opt_no_duplicates": "PDF amb fonts i imatges optimitzades",
        "help_opt_title": "Opcions d’optimització PDF",
        "help_opt_no_optimize": "Més ràpid, mida d'arxiu gran",
        "help_opt_standard": "Més lent, mida d'arxiu intermèdia",
        "help_opt_no_duplicates": "Bastant lent, mida d'arxiu mínima",
        "LICENSE_NOTICE": "Aquest programa és programari lliure: podeu redistribuir-lo i/o modificar-lo sota els termes de la Llicència Pública General Affero de GNU (AGPL), versió 3. Es distribueix SENSE CAP GARANTIA; consulteu la llicència a gnu.org/licenses/agpl-3.0.html",
    },
}


def get_text(lang_code: str, key: str, *args) -> str:
    """Obtiene el texto traducido según el código de idioma y la clave."""
    lang = LANGUAGES.get(lang_code, LANGUAGES["es"])
    text = lang.get(key, LANGUAGES["es"].get(key, key))

    if args:
        try:
            return text.format(*args)
        except Exception:
            return text
    return text


# Alias de compatibilidad para evitar el ImportError desde color_design.py
def t(key: str, *args) -> str:
    return get_text("es", key, *args)
